TRANSIT_ACCESS_MODES = ("WALK",)
TRANSIT_EGRESS_MODES = ("WALK",)
TRANSIT_DIRECT_MODES: tuple[str, ...] = ()
TRANSIT_AGENT_WALKING_MODE = "walking"
TRANSIT_MAX_ACCESS_SECONDS = 900
TRANSIT_MAX_EGRESS_SECONDS = 900


__all__ = [
    "TRANSIT_ACCESS_MODES",
    "TRANSIT_AGENT_WALKING_MODE",
    "TRANSIT_DIRECT_MODES",
    "TRANSIT_EGRESS_MODES",
    "TRANSIT_MAX_ACCESS_SECONDS",
    "TRANSIT_MAX_EGRESS_SECONDS",
]
